# SPDX-FileCopyrightText: 2025 Systems and Multimedia Lab @ Rutgers University
# SPDX-License-Identifier: Apache-2.0
#
# This file is part of the 👁️NavGS (EyeNavGS) project.
# See LICENSE_EYENAVGS.txt and NOTICE for details.


import csv
import json
import math
import argparse
import numpy as np
from scipy.spatial.transform import Rotation

def csv_to_json(csv_path, json_path, width, height):
    """
    Converts a CSV file back to the original JSON format

    Args:
        csv_path (str): Path to the input CSV file
        json_path (str): Path for the output JSON file
        width (int): The original image width, required for calculations
        height (int): The original image height, required for calculations
    """
    reconstructed_frames = []

    try:
        with open(csv_path, 'r', newline='') as f:
            reader = csv.DictReader(f)
            for i, row in enumerate(reader):
                if i % 2 == 0: continue
                position = [
                    float(row['PositionX']),
                    -float(row['PositionY']),
                    -float(row['PositionZ'])
                ]

                csv_w = float(row['QuaternionW'])
                csv_x = float(row['QuaternionX'])
                csv_y = float(row['QuaternionY'])
                csv_z = float(row['QuaternionZ'])

                quat_x = csv_x
                quat_y = -csv_y
                quat_z = -csv_z
                quat_w = csv_w

                r = Rotation.from_quat([quat_x, quat_y, quat_z, quat_w])
                rotation_matrix = r.as_matrix().tolist()

                fov_x_rad = float(row['FOV2']) - float(row['FOV1'])
                fov_y_rad = float(row['FOV4']) - float(row['FOV3'])
                
                fx = width / (2 * math.tan(fov_x_rad / 2))
                fy = height / (2 * math.tan(fov_y_rad / 2))

                euler = r.as_euler('xyz', degrees=True)
                frame = {
                    "tMs": int(row['timestep']),
                    "durationMs": 0,
                    "angle": euler[2],
                    "elevation": euler[1],
                    "x": position[0],
                    "y": position[1],
                    "z": position[2],
                    "fy": fy,
                    "fx": fx,
                    "cx": width / 2,
                    "cy": height / 2,
                    "width": width,
                    "height": height,
                    "profile": 0
                }
                reconstructed_frames.append(frame)
                if i > 1:
                    reconstructed_frames[-2]["durationMs"] = reconstructed_frames[-1]["tMs"] - reconstructed_frames[-2]["tMs"]

            reconstructed_frames[-1]["durationMs"] = reconstructed_frames[-2]["durationMs"]

        with open(json_path, 'w') as f_out:
            json.dump(reconstructed_frames, f_out, indent=4)
        
        print(f"✅ SUCCESS: Reconstructed {len(reconstructed_frames)} frames.")
        print(f"   - Input:  {csv_path}")
        print(f"   - Output: {json_path}")

    except FileNotFoundError:
        print(f"❌ ERROR: Input file not found at {csv_path}")
    except KeyError as e:
        print(f"❌ ERROR: CSV is missing a required column: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert a CSV trace back to its original JSON format.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument("input_csv", help="Path to the CSV file generated by the C++ program.")
    parser.add_argument("output_json", help="Path to write the reconstructed JSON file.")
    parser.add_argument("--width", type=int, required=True, help="Original image width (e.g., 1297). This is required.")
    parser.add_argument("--height", type=int, required=True, help="Original image height (e.g., 840). This is required.")
    
    args = parser.parse_args()
    csv_to_json(args.input_csv, args.output_json, args.width, args.height)

# Example usage:
# python csv_to_json.py input.csv output.json --width 1297 --height 840
